### PR TITLE
fix: change default config

### LINKED ISSUE #5: change default codefolding behavior
code gets folded by default, shouldn't be the case I guess

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
change default config to disable folding by default closes #5

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
also fixes env variable for windows

**Comment by antfu** [comment]
Can you somehow point where you made the changes? Thanks, it's really hard to find the difference here 😅

**Comment by alexanderniebuhr** [comment]
Package.json 141
And added cross env

**Review by voorjaar — COMMENTED** [review]
Sorry bro, I don't think we need cross-env, the old method works well.

**Comment by voorjaar** [comment]
Well, we need cross-env, but this tab is a little bad. So I will add it myself and create a editorconfig...

**Pull request closed without merging**
